Update rngen

diff --git a/scripts/ps/rngen b/scripts/ps/rngen
--- a/scripts/ps/rngen
+++ b/scripts/ps/rngen
@@ -27,6 +27,8 @@ latest tag to the current HEAD.
 $(color 3 OPTIONS)
 $(color 2 "-b|--branch") BRANCH     The git branch to operate on (default HEAD)
 $(color 2 "-c|--close-jira")        Closes all jira issues
+$(color 2 "-f|--force-deploy")      Add [force deploy] to tag messages and deploy even if there
+                                      are no PRs to generate notes for.
 $(color 2 "-h|--help")              Show this help message
 $(color 2 "-i|--interactive")       Review release notes interactively. Interactive output is 
                          sent to STDERR so notes can still be piped
@@ -157,6 +159,14 @@ jira_close() {
   fi
 }
 
+jira_comment() {
+  if ! command -v jira >/dev/null 2>&1; then
+    jira-terminal comment --body "$2" --ticket "$1" > /dev/null
+  else
+    jira issue comment add "$1" "$2" --no-input > /dev/null
+  fi
+}
+
 if ! command -v gh-changelog > /dev/null; then
   error_exit 'gh-changelog is required https://github.com/justinhoward/misc-scripts/blob/master/bin/gh-changelog'
 fi
@@ -177,8 +187,8 @@ if ! command -v jq > /dev/null; then
   error_exit 'The jq JSON parser is required https://stedolan.github.io/jq/'
 fi
 
-shortopts='b:chiNo:pr:s:tTv'
-longopts='branch:,close-jira,help,interactive,no-color,owner:,previous-release,repo:,max-skips:,tag,signed-tag,verbose'
+shortopts='b:cfhiNo:pr:s:tTv'
+longopts='branch:,close-jira,force-deploy,help,interactive,no-color,owner:,previous-release,repo:,max-skips:,tag,signed-tag,verbose'
 
 if ! getopt -T > /dev/null; then
   options="$(getopt \
@@ -200,6 +210,7 @@ while true; do
   case "$1" in
     -b|--branch) changelog_opts+=(-b "$2"); branch="$2"; shift 2;;
     -c|--close-jira) close_jira=1; shift ;;
+    -f|--force-deploy) force_deploy=1; shift ;;
     -h|--help) help=1; shift ;;
     -i|--interactive) interactive=1; shift ;;
     -N|--no-color) no_color=1; shift ;;
@@ -243,7 +254,6 @@ fi
 changelog_list=()
 detail_list=()
 jira_issues=()
-last_pr_number="0"
 for line in "${changelog_json[@]}"; do
   title="$(echo "$line" | jq -r .title)"
   number="$(echo "$line" | jq -r .number)"
@@ -251,104 +261,95 @@ for line in "${changelog_json[@]}"; do
   body="$(echo "$line" | jq -r .body)"
   head_branch="$(echo "$line" | jq -r .head.ref)"
   gh_url="$(echo "$line" | jq -r .html_url)"
-  pr_jira_issues=($(echo "$title $body $head_branch" | grep -oE '[A-Z]{2,8}-[0-9]{1,6}' | sort -u))
-  if [ "${#pr_jira_issues[@]}" == "0" ]; then
-    pr_jira_issues=("")
+  jira_issue="$(echo "$title $body $head_branch" | grep -oE '[A-Z]{2,8}-[0-9]{1,6}' | head -1)"
+  if [ -n "$jira_issue" ]; then
+    jira_issues+=("$jira_issue")
+    set -o pipefail
+    if ! jira_detail="$(jira_issue_detail "$jira_issue")"; then
+      jira_detail=
+      jira_issue=
+    fi
+    set +o pipefail
   fi
-  for jira_issue in "${pr_jira_issues[@]}"; do
-    if [ -n "$jira_issue" ]; then
-      jira_issues+=("$jira_issue")
-      jira_issues+=("$jira_issue")
-      set -o pipefail
-      if ! jira_detail="$(jira_issue_detail "$jira_issue")"; then
-        jira_detail=
-        jira_issue=
+
+  if [ -n "$jira_issue" ]; then
+    description="$(jira_summary_from_detail "$jira_detail")"
+  else
+    description="$title"
+  fi
+
+  if [ -n "$interactive" ]; then
+    while true; do
+      msg "GitHub #$number $title by $user"
+      if [ -n "$jira_issue" ]; then
+        msg "$jira_issue $(echo "$jira_detail" | head -1)"
       fi
-      set +o pipefail
-    fi
+      msg "Description: $description"
 
-    if [ -n "$jira_issue" ]; then
-      description="$(jira_summary_from_detail "$jira_detail")"
-    else
-      description="$title"
-    fi
-
-    if [ -n "$interactive" ]; then
-      while true; do
-        msg "GitHub #$number $title by $user"
-        if [ -n "$jira_issue" ]; then
-          msg "$jira_issue $(echo "$jira_detail" | head -1)"
-        fi
-        msg "Description: $description"
-
-        prompt="($(color 4 d))one,($(color 4 m))ore,($(color 4 e))dit,($(color 4 s))kip,($(color 4 g))ithub"
-        [ -n "$jira_issue" ] && prompt+=",($(color 4 j))ira"
-        read -r -p "$prompt: " answer
-        msg
-        case "$answer" in
-          d|done)
-            break
-            ;;
-          m|more)
-            (
-              cat <<EOF
+      prompt="($(color 4 d))one,($(color 4 m))ore,($(color 4 e))dit,($(color 4 s))kip,($(color 4 g))ithub"
+      [ -n "$jira_issue" ] && prompt+=",($(color 4 j))ira"
+      read -r -p "$prompt: " answer
+      msg
+      case "$answer" in
+        d|done)
+          break
+          ;;
+        m|more)
+          (
+            cat <<EOF
 $(color 2 "GitHub #$number $title by $user")
 $(color 2 ─────────────────────────────────────────────────────────────────)
 $body
 EOF
 
-              if [ -n "$jira_issue" ]; then
-                cat <<EOF
+            if [ -n "$jira_issue" ]; then
+              cat <<EOF
 
 $(color 2 "$jira_issue")
 $(color 2 ─────────────────────────────────────────────────────────────────)
 $jira_detail
 EOF
-              fi
-            ) | sed 's/\r$//' | "$PAGER"
-            ;;
-          e|edit)
-            read -r -p "Description: " -e new_description
-            [ -n "$new_description" ] && description="$new_description"
-            ;;
-          s|skip)
-            description=""
-            break
-            ;;
-          j|jira)
-            if [ -n "$jira_issue" ]; then
-              open_url "$(jira_url "$jira_issue")"
-            else
-              err "No Jira issue to open"
             fi
-            ;;
-          g|github)
-            open_url "$gh_url"
-            ;;
-          *)
-            err "Invalid option $answer"
-            ;;
-        esac
-      done
-    fi
+          ) | sed 's/\r$//' | "$PAGER"
+          ;;
+        e|edit)
+          read -r -p "Description: " -e new_description
+          [ -n "$new_description" ] && description="$new_description"
+          ;;
+        s|skip)
+          description=""
+          break
+          ;;
+        j|jira)
+          if [ -n "$jira_issue" ]; then
+            open_url "$(jira_url "$jira_issue")"
+          else
+            err "No Jira issue to open"
+          fi
+          ;;
+        g|github)
+          open_url "$gh_url"
+          ;;
+        *)
+          err "Invalid option $answer"
+          ;;
+      esac
+    done
+  fi
 
-    if [ -n "$description" ]; then
-      detail_line="- $(echo "$description" | tr '[' '(' | tr ']' ')')"
-      if [ -n "$jira_issue" ]; then
-        detail_line+=" [$jira_issue]($(jira_url "$jira_issue"))"
-      else
-        detail_line+=" (no Jira)"
-      fi
-      detail_list+=("$detail_line")
-      if [ "$last_pr_number" != "$number" ]; then
-        changelog_list+=("- ${title} #${number} ${user}")
-        last_pr_number=$number
-      fi
+  if [ -n "$description" ]; then
+    detail_line="- $(echo "$description" | tr '[' '(' | tr ']' ')')"
+    if [ -n "$jira_issue" ]; then
+      detail_line+=" [$jira_issue]($(jira_url "$jira_issue"))"
+    else
+      detail_line+=" (no Jira)"
     fi
-  done
+    detail_list+=("$detail_line")
+    changelog_list+=("- ${title} #${number} ${user}")
+  fi
 done
 
-if [ "${#changelog_list[@]}" -gt 0 ]; then
+if [ "${#changelog_list[@]}" -gt 0 ] || [ -n "$force_deploy" ]; then
   if [ -n "$tag_flag" ] || [ -n "$previous_release" ]; then
     repo_name="$(gh repo view --json name --jq .name)"
   fi
@@ -366,18 +367,29 @@ if [ "${#changelog_list[@]}" -gt 0 ]; then
     printf '%s `%s`\n\n' "$repo_name" "$tag_name"
   elif [ -n "$previous_release" ]; then
     # shellcheck disable=2016
+    tag_name="$latest"
     printf '%s `%s`\n\n' "$repo_name" "$latest"
   fi
 
-  detail_msg="$(printf '%s\n' "${detail_list[@]}")"
-  printf '%s\n' "$detail_msg"
+  if [ "${#detail_list[@]}" -gt 0 ]; then
+    detail_msg="$(printf '%s\n' "${detail_list[@]}")"
+    printf '%s\n' "$detail_msg"
+  fi
 
-  changelog_msg="$(printf '%s\n' "${changelog_list[@]}")"
-  # shellcheck disable=2016
-  printf '\n```\n%s\n```\n' "$changelog_msg"
+  if [ "${#changelog_list[@]}" -gt 0 ]; then
+    changelog_msg="$(printf '%s\n' "${changelog_list[@]}")"
+    # shellcheck disable=2016
+    printf '\n```\n%s\n```\n' "$changelog_msg"
+  fi
 
   if [ -n "$tag_flag" ]; then
-    tag_msg="$(printf 'Release %s\n\n%s' "$tag_name" "$changelog_msg")"
+    tag_title="$tag_name"
+    if [ -n "$force_deploy" ]; then
+      err "--force-deploy flag is set, adding [force deploy] to the tag message"
+      tag_title+=' [force deploy]'
+    fi
+
+    tag_msg="$(printf 'Release %s\n\n%s' "$tag_title" "$changelog_msg")"
     git tag -"$tag_flag" -m "$tag_msg" "$tag_name"
 
     msg "Tagged release $tag_name"
@@ -395,6 +407,7 @@ fi
 if [ -n "$close_jira" ]; then
   jira_issues_unique=$(printf "%s\n" "${jira_issues[@]}" | sort -u)
   for issue in "${jira_issues_unique[@]}"; do
+    jira_comment "$issue" "Release: $repo_name $tag_name"
     jira_close "$issue" && msg "Closed $issue"
   done
 fi
